/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardDiv: typeof import('./src/components/CardDiv.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchBottom: typeof import('./src/components/switchBottom.vue')['default']
    VerifyDiv: typeof import('./src/components/verifyDiv.vue')['default']
  }
}
